# Documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # the test javascript lambda function
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
